# Site settings
title: Rado Pitonak
description: Personal page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://rpitonak.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rado Pitonak
user_description: Hi! My name is Rado Pitonak and I am co-founder of Zaitra - space company focused on Artificial Intelligence and Earth Observation. Before I decided to start a company I worked as a software engineer at Red Hat. I earned my undergraduate degree at Brno University of Technology with my bachelor thesis on topic - Deep learning for object detection. I am technology and open-source enthusiast with experience mainly in Python programming language.
user_title: Software Developer
email: rado@zaitra.io
twitter_username: radopitonak
github_username:  rpitonak



# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
